[package]
name = "iced_lazy"
version = "0.1.0"
edition = "2021"

[features]
pure = ["iced_pure"]

[dependencies]
ouroboros = "0.13"

[dependencies.iced_native]
version = "0.4"
path = "../native"

[dependencies.iced_pure]
version = "0.1"
path = "../pure"
optional = true
