[package]
name = "iced_pure"
version = "0.1.0"
edition = "2021"

[dependencies]
iced_native = { version = "0.4", path = "../native" }
iced_style = { version = "0.3", path = "../style" }
num-traits = "0.2"
